# Generated by Django 2.2.18 on 2021-08-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pogoda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='temperature',
            field=models.IntegerField(null=True),
        ),
    ]
